### ISSUE TITLE
Is the dev branch still current?

### ISSUE THREAD

**Issue by pierreozoux** [tosdr/tosdr2#10]
What is the purpose of the dev branch?

Is it really necessary?

I just see that they diverged :/

**Comment by michielbdejong** [comment]
Yes! Oh bummer, I should have merged that. Please cherry-pick the following important bugfixes into master:
https://github.com/tosdr/tosdr2/commit/14a9c5a6dcb1306e2f45da9f78cd54f0eb9da903
https://github.com/tosdr/tosdr2/commit/1d567faea4270b130ec579c4594414d6ac55d78c (I think this one was already done in master as well)
https://github.com/tosdr/tosdr2/commit/741880b2856b3071132c3011b32be033f4f0f735
https://github.com/tosdr/tosdr2/commit/fabc316037c6d830fbba6b1059387cd15050b8b1
https://github.com/tosdr/tosdr2/commit/2450ba9c6fc4ee4d15a492b09bb441fd0bf88790
https://github.com/tosdr/tosdr2/commit/2b15a9461798e1198f64be4b5e08f82983fff730
https://github.com/tosdr/tosdr2/commit/fa8e8c01bbacdb0295a754ad2f7629cbdade5861

**Comment by michielbdejong** [comment]
the rest of the dev branch is probably no longer mergable after your hosting cleanup, but just read through [each of them](https://github.com/tosdr/tosdr2/commits/dev) to make sure that you are doing something equivalent.

Sorry, I had forgotten that all the recent work was in the dev branch and not in master. :/

**Comment by michielbdejong** [comment]
Closed means done? Great! I hope it didn't cause you too much work to rebase and merge? Sorry again I hadn't thought of this before you started!

**Comment by pierreozoux** [comment]
No that's fine :)
