### ISSUE TITLE
Have a web interface to make users moderator

### ISSUE THREAD

**Issue by pierreozoux** [tosdr/tosdr2#12]
To remove this piece from the README: https://github.com/tosdr/tosdr2#how-to-make-a-user-to-a-moderator

I think to use a general purpose admin interface to do so.
For another project I used that:  https://github.com/gterrono/houston

It would require 2 mins to setup, and is handy to do anything with the app (but you need to be extra careful). This would be some kind of super admin.

It would allow people to perform tasks that normally require the command line.

**Comment by michielbdejong** [comment]
making a person moderator is something we would do maybe once or twice per year, so it's nice and secure in a way if that can only be done by the server administrator (you). so the way it is now, via the command line is fine for that, i think.

**Comment by pierreozoux** [comment]
ok, fine :)
