### ISSUE TITLE
list unmoderated points per service

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosdr2#13]
these are some screenshots from [the current moderator tool](https://github.com/tosdr/tosdr-build/blob/master/scripts/curator.js), it would be nice if moderators can list the points that need moderating per service, so you can do all pending points for one service and then assign a class to it if all topics have been covered for that service.
![curator-submit](https://cloud.githubusercontent.com/assets/408412/8567119/09af88ea-2563-11e5-9969-ef9fe6782cdd.png)
![curator-main](https://cloud.githubusercontent.com/assets/408412/8567120/09b4c404-2563-11e5-8bcc-d80f70c11e6b.png)

**Comment by michielbdejong** [comment]
it's a nice test to see if the points displayed are exactly the same ones as those that the existing moderator tool displays, then you know that the data has been imported correctly into the database.

**Comment by pierreozoux** [comment]
For now, you can list all unapproved points,  but not by service.

Do you think it is a critical feature or just a noce to have?

Also, about the import, do you think that the `approved status` is in the exported data set? Because there is no unapproved points.

**Comment by michielbdejong** [comment]
Sure, unsorted is fine for now. Let's get something working first.

The way the buildIndexes script decides what to display and what not, is that a point is approved if it has all the necessary fields. If some fields are missing, then it's unapproved. :) So yeah, it will make sense to add some data field 'approved by moderator so-and-so', and make that an extra requirement before a point is displayed.

Let's see what happens (what git diff we get) if we approve one point and build the site.

**Comment by pierreozoux** [comment]
What about having a reactive table instead of a nested list.

I use this plugin with another project, and I'm quiet happy!

https://github.com/aslagle/reactive-table

**Comment by michielbdejong** [comment]
Sounds good, because the 'all points' view is very slow now.

**Comment by pierreozoux** [comment]
Ok, what do you think of the new layer?

https://test-tosdr2.tokoloho.co/points

If you like it, I'll then apply it to `services` and `topic`.

**Comment by michielbdejong** [comment]
Nice, big improvement!! :)

**Comment by pierreozoux** [comment]
Ok, let's close this in favor of #20
