### ISSUE TITLE
Translatable!

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr2#14]
This is actually a very important feature: we want to span several initiatives to achieve world domination ;-)

So, when a group of French people want to start ToS;DR on French websites and French ToS (in the French language) they can take the source code, configure it to "French" (or translate the interface with something maintainable if French is not yet available) and start their own initiative.

The sooner we think on how to achieve this, the easier it will be.

I consider this one of the most important feature TBH. Because if several initiatives bootstrap, that means more attention, more developers, more interest to improve the codebase.

**Comment by pierreozoux** [comment]
Ok, after studying a bit, I'll go with https://github.com/TAPevents/tap-i18n

IMHO, french people could use the same website. Let's say they want to rate `laposte.net`, they'll go to our webinterface, create a new entry in french. It;s totally fine as people checking for the tos of such service will be probably french :)

But if they want to run on their own server, they are of course free to do so!

**Comment by hugoroy** [comment]
> IMHO, french people could use the same website. Let's say they want to rate laposte.net, they'll go to our webinterface, create a new entry in french. It;s totally fine as people checking for the tos of such service will be probably french :)

So what if they want to read about Google's ToS in French?

Also, an English company might be interested in using a French service too for many reasons. So Laposte.net should also be rated in English if it's of interest to an English-speaking audience.

I think we do not want to mix different languages on 1 page.

**Comment by pierreozoux** [comment]
Ok, I just finnished i18n support for the interface. It means that it is possible and easy to translate tosdr2. (no options yet to select the language from the interface)

We can start translating here :)
https://www.transifex.com/projects/p/tosdr2/

About `GoogleTos in french` feature.
I see 3 options:
- 1 point and i18n of title and summary: meaning that for each point we'll try to localize it.
- 1 point is a point, we add a language field, so if you choose french, you might not have the same points a if you would have choosed english
- tosdr2 stays in english but people are free to setup their own server and use tosdr2 for their community in their language.

I think the 1st option is the best, but it would require some deep changes in the application (not impossible though :) ).

**Comment by hugoroy** [comment]
I've always leaned towards option #3.

**Comment by michielbdejong** [comment]
As a side-note, I think it's not so useful to translate the buttons in the Meteor app if we don't (also) translate the html that is generated for the tosdr.org site itself by https://github.com/tosdr/tosdr-build/blob/master/build/renderPages.js

If the html on the main static site is not translated, then people who don't speak English will never even reach the Meteor app.

**Comment by hugoroy** [comment]
## Yes, I assumed everything would go in the metetor app including the homepage.

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by michielbdejong** [comment]
That's not the case. We have three relevant repos here: tosdr2 (the meteor app), tosdr-build (the grunt process that converts JSON into html), and the tosdr.org repo (static content we push to 5apps).

The way it works with the meteor app is:
- meteor app generates master data in its mongodb database
- there is a button somewhere in the meteor app that exports the database to JSON files
- if the meteor app is installed next to a checked-out copy of the tosdr-build repo, then it can save the JSON files directly in the right place in the `src/` folder of the tosdr-build repo
- then you can do a `git diff` on the tosdr-build repo to see what changed
- if it looks ok, commit it, and run `grunt` in the root of the tosdr-build repo
- this will in turn generate static html in the `dist/` folder of the tosdr-build repo.
- if the `dist/` folder is a check-out of the tosdr.org repo, then you can cd into it, check if the git diff makes sense, commit, push to github, and push to 5apps.

So the meteor app does not directly generate tosdr.org, it has its own mongodb database and is able to export that to the format of the tosdr-build repo, and then there is the grunt step, which is still essential.

So it's [tosdr2]-> mongodb ->[export]-> JSON ->[tosdr-build grunt]-> html ->[git push 5apps master]-> live version of tosdr.org.

**Comment by hugoroy** [comment]
Wouldn't it make sense to merge the meteor app with tosdr- build in the future?

I am afraid that making it too complex for no good reason might not encourage participants

Le 16 juillet 2015 11:52:54 GMT+02:00, Michiel de Jong notifications@github.com a écrit :

> That's not the case. We have three relevant repos here: tosdr2 (the
> meteor app), tosdr-build (the grunt process that converts JSON into
> html), and the tosdr.org repo (static content we push to 5apps).
> 
> The way it works with the meteor app is:
> - meteor app generates master data in its mongodb database
> - there is a button somewhere in the meteor app that exports the
>   database to JSON files
> - if the meteor app is installed next to a checked-out copy of the
>   tosdr-build repo, then it can save the JSON files directly in the right
>   place in the `src/` folder of the tosdr-build repo
> - then you can do a `git diff` on the tosdr-build repo to see what
>   changed
> - if it looks ok, commit it, and run `grunt` in the root of the
>   tosdr-build repo
> - this will in turn generate static html in the `dist/` folder of the
>   tosdr-build repo.
> - if the `dist/` folder is a check-out of the tosdr.org repo, then you
>   can cd into it, check if the git diff makes sense, commit, push to
>   github, and push to 5apps.
> 
> So the meteor app does not directly generate tosdr.org, it has its own
> mongodb database and is able to export that to the format of the
> tosdr-build repo, and then there is the grunt step, which is still
> essential.
> 
> So it's [tosdr2]-> mongodb ->[export]-> JSON ->[tosdr-build grunt]->
> html ->[git push 5apps master]-> live version of tosdr.org.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tosdr/tosdr2/issues/14#issuecomment-121911395

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
