### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by pierreozoux** [tosdr/tosdr2#19]
Yep!

@michielbdejong @hugoroy, I just put you as moderator on https://test-tosdr2.tokoloho.co/ for you to test the moderator part.

What is missing according to you to go to production?

On my side, to go to production, I need:
- a TLS cert (I'll provide the csr)
- an smtp server (with credentials to send emails)
- a subdomain pointing to my dns server (the NS entries)

Please let me know if you need anything else on my side!

Pierre

**Comment by michielbdejong** [comment]
Re TLS cert, smtp server, and subdomain:
- I have a startssl cert already for edit.tosdr.org, let's use that. I'll scp it to your server, let's arrange via irc.
- I'll look up the credentials of the sendgrid account that tosback.org uses. I think it's free of charge up to 60 emails a day or something, so that's probably fine for now.
- Then I'll also point DNS for edit.tosdr.org to your server.

Other next steps:
- Make sure the data is exactlly the same as what's displayed by the old moderator tool (I can have a look at this)
- Try editing one point and publishing the change to the website. You will need a 5apps account for that, can you sign up on 5apps.com?

**Comment by michielbdejong** [comment]
@pierreozoux I don't remember what user I had so far, I now created 'michiel@unhosted.org' on https://test-tosdr2.tokoloho.co/, can you make that user moderator instead of my old test user?

**Comment by pierreozoux** [comment]
(done for your user)

For the DNS, please point NS record of the subdomain to:

```
freedns1.registrar-servers.com
freedns2.registrar-servers.com
freedns3.registrar-servers.com
freedns4.registrar-servers.com
freedns5.registrar-servers.com
```

My 5apps username:  pierreozoux@5apps.com 

For the rest (cert, sendgrid, DNS), I let you do it :)

Once done, I'll try to publish.

**Comment by michielbdejong** [comment]
@hugoroy can you log in to https://5apps.com/deploy/apps/512cb93cbc73cb2f84000002/settings/collaborators as the tosdr user there and give pierreozoux deploy access?

**Comment by pierreozoux** [comment]
And here you are!
https://edit.tosdr.org/

**Comment by hugoroy** [comment]
Done ☺

## 

Hugo Roy  
Project Lead, Terms of Service; Didn't Read https://www.tosdr.org

Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by hugoroy** [comment]
Just subscribed with hugo at tosdr.org :) please make me a
moderator/admin too

## 

Hugo Roy  
Project Lead, Terms of Service; Didn't Read https://www.tosdr.org

Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by pierreozoux** [comment]
@michielbdejong and @hugoroy please create an account on the edit.tosdr.org (production) and then I can make you moderator.

Michiel, about the next steps:
- Other next steps:
  - `Make sure the data is exactlly the same as what's displayed by the old moderator tool`: can you explain me or do it?
- `Try editing one point and publishing the change to the website.` I don't wan to mess the production, so please do one, or explain me, and then I'll push to prod.

Danke!

**Comment by michielbdejong** [comment]
ok, please make michiel@tosdr.org a moderator account so I can have a look and compare.

One thing you can do now already is to try running `grunt` in the tosdr-build repo, and see how it touches the tosdr.org content in its `dist/` folder.

**Comment by pierreozoux** [comment]
Ok :) Done!

Ok, I'll take a look to grunt.

**Comment by michielbdejong** [comment]
yeah, as discussed, `scripts/curator.js` displays >100 unmoderated points, and edit.tosdr.org currently shows zero, so that needs fixing. The list should match exactly before we can continue.

**Comment by pierreozoux** [comment]
@michielbdejong I opened #20 to be fixed before production.

**Comment by hugoroy** [comment]
Can you deploy on edit.tosdr.org?

**Comment by hugoroy** [comment]
OK, it's deployed. Let's deploy regularly?
