### ISSUE TITLE
Please FIX license

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr2#2]
Please add the AGPL-3 or later license (same as tosdr-build).

cc @shybyte

**Comment by hugoroy** [comment]
This must be added by @shybyte actually as he's the main author

**Comment by shybyte** [comment]
@hugoroy I added it to the original repo https://github.com/shybyte/tosdr2. Is this OK?

**Comment by hugoroy** [comment]
Yes. Thank you!

**Comment by hugoroy** [comment]
@shybyte Actually, can you add in the README that the license is "AGPL version 3 or any later version approved for ToS;DR, see https://tosdr.org/legal.html"

See the last section in https://github.com/tosdr/tosdr-build/ README
