### ISSUE TITLE
Import script - unmoderated points

### ISSUE THREAD

**Issue by pierreozoux** [tosdr/tosdr2#20]
The import script doesn't import properly the non moderated points.

If you compare:
https://github.com/tosdr/tosdr-build/blob/master/scripts/curator.js

It shows > 100points to be moderated

and in tosdr2 there are none to be moderated after import.

**Comment by pierreozoux** [comment]
Ok, I finally managed: now the unmoderated points appear in test:
(I also added reactive-table to services and topic)

https://test-tosdr2.tokoloho.co/points

(you can check the difference with https://edit.tosdr.org )

@michielbdejong @hugoroy  please let me know, then we can close this, and announce to the world that the app is ready!

**Comment by michielbdejong** [comment]
@pierreozoux ok, will try it out!

**Comment by michielbdejong** [comment]
Hi @pierreozoux I logged in to  and saw this point as the top one:

> FW: Hugo Roy (@hugoroyd) replied to one of your Tweets! (service: Four+square)

That same point does not show up on http://localhost:21337/ when I run `node scripts/curator.js`. Does it show up when you run it? It shouldn't, because that point has `irrelevant: true` set in its JSON file.

I just emailed you the list of JSON files the curator displays when I run `node scripts/curator.js` - is it different for you? Or did you maybe not get it running? Let me know if I can help further!

Cheers,
Michiel.

**Comment by michielbdejong** [comment]
@pierreozoux ping

**Comment by michielbdejong** [comment]
Ah, just saw your email, sorry. :)
OK, I'll create a new ticket about the tooling decision.

**Comment by pierreozoux** [comment]
I'm on it, but it is really messy and so, difficult to understand.

If I have questions, I'll send an email.

**Comment by michielbdejong** [comment]
Yes, there are a lot of checks involved! Just read the nodejs code of `scripts/curator.js` and you should be able to use the same checks in Meteor.

**Comment by pierreozoux** [comment]
At the end I removed 'approved' concept. It was to vague.
For instance, a point that is irrelevant is not approved but do not need moderation.

So I created 2 new concepts: needModeration and publishable.

Here is the [needModeration](https://github.com/tosdr/tosdr2/blob/master/lib/collections.js#L18-L29).
If everything is fine, I'll update the export script.

I'll deploy right now on edit.tosdr.org if you want to try.

I close this for now, I think it is fixed.

**Comment by michielbdejong** [comment]
You can check yourself if the two lists are exactly identical. Are they?

**Comment by hugoroy** [comment]
BTW, can you join irc?

**Comment by pierreozoux** [comment]
@michielbdejong there aren't, but as the curator was not listing points without point nor score, then I think thaat's fine. Adn if we see a problem in the future, we could adjust.

**Comment by michielbdejong** [comment]
@pierreozoux so the best test is to uncomment those two lines in curator.js and check if you get an exact match then.
