### ISSUE TITLE
Tooling decision

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/tosdr2#21]
We have to make a decision between continuing to develop this Meteor tool, or switching to Wagn (the tool powering wikirate.org)

**Comment by michielbdejong** [comment]
I'm in favor of sticking to Meteor. We have a system that we're almost ready to start using (just need to finish the data import, #20), and the reason that this has not been completed yet is not that it's a lot of work, just that I had too many other things to do. But we have @pierreozoux now, so that problem is solved.

The code reuse argument may be misleading. Meteor is a much bigger project than Wagn, and although it may look like it's not so specific to what we need, the amount of own code that we need to put on top of Meteor is actually really small. If anything is reusable, then there will be a Meteor plugin for it, and this is probably not true for Wagn. Just search for things like 'meteor upvote' or 'meteor rating' and you'll see how much reusable code is out there! :)

Switching to Wagn now would mean going back to zero (where we were a year ago), and also suddenly relying on a small startup instead of on a worldwide community. It's also likely that Meteor is a lot more stable than Wagn, and if we run into problems with Meteor bugs, we can just find the solution on stackoverflow. If we run into bugs with Wagn, we pretty much hang by the balls. ;)

Also, none of the things that are currently missing from this app can be solved by Wagn.

So I would say, let's close #20 (can probably be done in one day) and ship! :)

**Comment by hugoroy** [comment]
Of course, if we're that close to something ready and usable by all ToS;DR contributors it's silly to stop now and go back to zero and a new system.

However, I wouldn't dismiss Wagn too early. What might be useful there is the synergy between the projects wikirate and tosdr and the fact that there's a team of people working on Wagn to make it work specifically for that kind of projects.

Let's keep an eye on this :-)

**Comment by pierreozoux** [comment]
I think that indeed we are really close to be able to launch a first version of the ToS;DR backend.
It would be a lot of work to start everything again from scratch.

I personally prefer to code in Meteor than in Rails.

**Comment by michielbdejong** [comment]
OK, so @pierreozoux can you continue working on #20, then? And at the same time we'll keep an eye on what the Wagn guys are doing.

**Comment by pierreozoux** [comment]
@michielbdejong ok
