### ISSUE TITLE
[feature] View/Discuss point

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr2#26]
It's possible to  edit a point (well sort of, see bug #25) -- but for non-moderators it shuold be possible to view a point (by just clicking on a line in https://edit.tosdr.org/points ) -- the 'view' interface should show the details of the point and of course offer a way to discuss the point. Discussions are one of the most important features. How do we handle that right now?

**Comment by pierreozoux** [comment]
For now, you can't view and there is no discussions.

**Comment by hugoroy** [comment]
## Until this is basically implemented we cannot move to this system

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
