### ISSUE TITLE
Edit point: summaries are emtpy

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr2#28]
example : https://edit.tosdr.org/points/edit/-CpUNz09iBo

**Comment by pierreozoux** [comment]
Nothing in this summary:
https://github.com/tosdr/tosdr-build/blob/master/src/points/-QKiBxXFQrI.json
Check this one:  https://edit.tosdr.org/points/edit/-BdGb47IMyM

**Comment by hugoroy** [comment]
But why are most of the points with no summary?!
