### ISSUE TITLE
Submit UI: what to do when a service's missing?

### ISSUE THREAD

**Issue by hugoroy** [tosdr/tosdr2#29]
User scenario: Submit a point about a new service

Right now, if the service is not in the database already, the user will simply be blocked from creating the point! It shouldn't be like that.

Creating a new service should be possible right from the submit point UI. We could auto-detect when the user is filling in a point that does not exist and make the "create new service" UI appear there (it's important that we do not redirect them to another UI but they can do it from the same UI I think, otherwise it's painful to jungle between multiple tabs and the risk to lose one and the input already there).

**Comment by michielbdejong** [comment]
this is fixed with #37.
