### ISSUE TITLE
Keep link for the fork?

### ISSUE THREAD

**Issue by pierreozoux** [tosdr/tosdr2#9]
Hi!

Do you want to keep the link from the fork or not? Just a little detail question. If you want to remove it, you have to send an email to support.

See this thread for more information: http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

If you want to keep like this, please just close this issue.

Best!

**Comment by michielbdejong** [comment]
Doesn't really matter, I guess? As long as issues are enabled in this repo, which they are.
